#
# Makefile for tegra baseband support.
#

#subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_BB_POWER)	+= bb-power.o
obj-$(CONFIG_TEGRA_BB_M7400)	+= bb-m7400.o
obj-$(CONFIG_TEGRA_BB_MODEM4)	+= bb-modem4.o
