# obj-$(CONFIG_LG_FW_MUIC_CONTROL_E920)		+= e920_switch_ctrl.o
#obj-$(CONFIG_LG_FW_MUIC_CONTROL_LVPROJECT)	+= lvproject_switch_ctrl.o
#obj-$(CONFIG_LG_FW_MUIC_MAX14526)		+= muic_max14526.o
#ifeq ($(CONFIG_LGE_COSMO_DRIVERS),y)
obj-$(CONFIG_LGE_MUIC)			+= muic.o
obj-$(CONFIG_LGE_MUIC)			+= muic_maxim.o
obj-$(CONFIG_LGE_MUIC)			+= muic_ti.o
obj-$(CONFIG_LGE_MUIC)      += fota.o
#endif
